name: Fullstack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies (Client)
        run: npm install
        working-directory: ./Client

      - name: Run lint (Client)
        run: npm run lint
        working-directory: ./Client

      - name: Build project (Client)
        run: npm run build
        working-directory: ./Client

  backend:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies (BackEnd)
        run: npm install
        working-directory: ./BackEnd

      # If you have ESLint for backend, uncomment this:
      # - name: Run lint (BackEnd)
      #   run: npm run lint
      #   working-directory: ./BackEnd

      - name: Run tests (BackEnd)
        run: npm test
        working-directory: ./BackEnd
